# Generated by Django 3.0.5 on 2021-03-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Numero', models.CharField(default='null', max_length=10)),
                ('Contenido', models.TextField()),
                ('Estado', models.BooleanField()),
                ('imagen', models.ImageField(default='null', upload_to='Article')),
            ],
            options={
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Despedida_soltera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Numero', models.CharField(default='null', max_length=10)),
                ('Contenido', models.TextField()),
                ('Estado', models.BooleanField()),
                ('imagen', models.ImageField(default='null', upload_to='Article')),
            ],
            options={
                'verbose_name': 'Despedida_soltera',
            },
        ),
        migrations.CreateModel(
            name='Jugetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Numero', models.CharField(default='null', max_length=10)),
                ('Contenido', models.TextField()),
                ('Estado', models.BooleanField()),
                ('imagen', models.ImageField(default='null', upload_to='Article')),
            ],
            options={
                'verbose_name': 'Jugete',
            },
        ),
        migrations.CreateModel(
            name='Lenceria_Hombres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Numero', models.CharField(default='null', max_length=10)),
                ('Contenido', models.TextField()),
                ('Estado', models.BooleanField()),
                ('imagen', models.ImageField(default='null', upload_to='Article')),
            ],
            options={
                'verbose_name': 'Lenceria_Hombre',
            },
        ),
        migrations.CreateModel(
            name='Lenceria_Mujeres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Numero', models.CharField(default='null', max_length=10)),
                ('Contenido', models.TextField()),
                ('Estado', models.BooleanField()),
                ('imagen', models.ImageField(default='null', upload_to='Article')),
            ],
            options={
                'verbose_name': 'Lenceria_Mujere',
            },
        ),
        migrations.CreateModel(
            name='Lubricante_cosmeticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Numero', models.CharField(default='null', max_length=10)),
                ('Contenido', models.TextField()),
                ('Estado', models.BooleanField()),
                ('imagen', models.ImageField(default='null', upload_to='Article')),
            ],
            options={
                'verbose_name': 'Lubricante_cosmetico',
            },
        ),
    ]
